# save model
#OUT_PATH_str: DGN/results/09Jan2023/SingleModel
log: debug
#
## save log
#log_path: DGN/logs/09Jan2023/SingleModel
#comment: fix_seed_GAT_repeat_2 # original_GAT


type_model: GCN
num_layers: [ 2 ] # [5, 60, 120]
type_norm: "None"
random_seeds: [ 200 ] # [100,200,300,400,500]
dataset: [ Cora] # ,Citeseer,Pubmed,CoauthorCS
dropedge: 0
skip: 0 # residual
skip_for_hyperplan: 0
cuda: True # False. True
cuda_num: 0
dropout: 0.6
lr: 0.005
weight_decay: !!float 5e-4
dim_hidden: 16
miss_rate: [0]
epochs: 1000
grad_clip: 0.0
num_groups: 10
residual: 0

#type_sphere_norm: "sphere_with_anchor"
type_layer: GCNConv_for_sphere_norm_with_anchor # GCNConv_for_sphere_norm_with_anchor, GATConv_for_sphere_norm_with_anchor
add_anchor: False

#simpleGCN_mode: sphere

#type_sphere_norm: "None"
#type_layer: None
#add_anchor: [False]

bias: False
last_layer_mode: None
bn_layer: useless

wm_fix: [False] # True,
b_constant: 0.9 # [0.3,0.5,0.7,0.9] # [0.3,0.5,0.7,0.9]

add_bn_layer_after: [0]